name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: List directory contents
      run: |
        ls -R AdvancedNotepad/android

    - name: Make gradlew executable
      run: chmod +x AdvancedNotepad/android/android/gradlew

    - name: Generate native_modules.gradle
      run: |
        cd AdvancedNotepad/android/android
        # If native_modules.gradle doesn't exist, create an empty one
        touch native_modules.gradle

    - name: Build with Gradle
      run: |
        cd AdvancedNotepad/android/android
        ./gradlew build
