name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Use Temurin JDK, formerly AdoptOpenJDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools-version: 30.0.3

      # Step 4: Install Node.js and dependencies in the root directory
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the appropriate Node.js version for your project

      - name: Install npm dependencies
        run: |
          npm install  # Install dependencies in the root directory

      # Step 5: Run postinstall script to ensure necessary files are linked
      - name: Run postinstall
        run: |
          npm run postinstall  # Link necessary files after install

      # Step 6: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 7: Build APK
      - name: Build APK
        run: |
          cd AdvancedNotepad/android/android  # Navigate to the Android directory
          chmod +x gradlew  # Ensure gradlew is executable
          ./gradlew assembleRelease  # Run Gradle build

      # Step 8: Upload APK as an artifact
      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: AdvancedNotepad/android/android/app/build/outputs/apk/release/app-release.apk
name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Use Temurin JDK, formerly AdoptOpenJDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools-version: 30.0.3

      # Step 4: Install Node.js and dependencies in the root directory
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the appropriate Node.js version for your project

      - name: Install npm dependencies
        run: |
          npm install  # Install dependencies in the root directory

      # Step 5: Run postinstall script to ensure necessary files are linked
      - name: Run postinstall
        run: |
          npm run postinstall  # Link necessary files after install

      # Step 6: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 7: Build APK
      - name: Build APK
        run: |
          cd AdvancedNotepad/android/android  # Navigate to the Android directory
          chmod +x gradlew  # Ensure gradlew is executable
          ./gradlew assembleRelease  # Run Gradle build

      # Step 8: Upload APK as an artifact
      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: AdvancedNotepad/android/android/app/build/outputs/apk/release/app-release.apk
