name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd AdvancedNotepad
        npm install

    - name: Copy gradle plugin
      run: |
        mkdir -p AdvancedNotepad/android/node_modules/@react-native
        cp -R AdvancedNotepad/node_modules/@react-native/gradle-plugin AdvancedNotepad/android/node_modules/@react-native/

    - name: Create native_modules.gradle
      run: |
        mkdir -p AdvancedNotepad/android/android
        echo "// This file is created by the GitHub Actions workflow" > AdvancedNotepad/android/android/native_modules.gradle

    - name: Update build.gradle
      run: |
        sed -i 's/compileSdkVersion = .*/compileSdkVersion = 33/' AdvancedNotepad/android/build.gradle

    - name: Make gradlew executable
      run: chmod +x AdvancedNotepad/android/android/gradlew

    - name: List directory contents
      run: |
        ls -R AdvancedNotepad/android

    - name: Build with Gradle
      run: |
        cd AdvancedNotepad/android/android
        ./gradlew build
