name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Use Temurin JDK, formerly AdoptOpenJDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'   # Use 'temurin' instead of 'adoptopenjdk'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools-version: 30.0.3

      # Step 4: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 5: Run Gradle Build (make sure to run it from the correct directory)
      - name: Build APK
        run: |
          cd AdvancedNotepad/android/android  # Navigate to the directory with gradlew.bat
          chmod +x gradlew  # Ensure the Gradle wrapper is executable
          ./gradlew assembleRelease  # Run Gradle build

      # Step 6: Upload APK as an artifact (optional)
      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: AdvancedNotepad/android/android/app/build/outputs/apk/release/app-release.apk
