name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: List directory contents
      run: |
        ls -R AdvancedNotepad

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd AdvancedNotepad
        npm install

    - name: Create symlink for gradle plugin
      run: |
        mkdir -p AdvancedNotepad/android/node_modules/@react-native
        ln -s ../../../../node_modules/@react-native/gradle-plugin AdvancedNotepad/android/node_modules/@react-native/gradle-plugin

    - name: Make gradlew executable
      run: chmod +x AdvancedNotepad/android/android/gradlew

    - name: Build with Gradle
      run: |
        cd AdvancedNotepad/android/android
        ./gradlew build
