name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Generate native_modules.gradle
      run: |
        cd AdvancedNotepad/android/android
        # Add commands to generate or copy the native_modules.gradle file
        # For example:
        # cp ../native_modules.gradle ./native_modules.gradle

    - name: Build with Gradle
      run: |
        cd AdvancedNotepad/android
        ./gradlew build
